### ISSUE TITLE
Initial D Zero - Force Feedback very tight

### ISSUE THREAD

**Issue by camborambo** [Boomslangnz/FFBArcadePlugin#10]
Hello,

I've been using this plugin for all the initial D games on teknoparrt and so far Initial D 4-8 works great. Initial D Zero keeps locking my logitech 920 to 100% force center spring and it's extremely stiff with no forcefeedback. I did try adjusting the values but nothing changes.

Unchecking the force force center spring option will allow the the force feedback to work but the steering is not playable as the spring would grip randomly to turn. Steering wheel is new and it works great on the other versions.

Importantly, thank you very much for creating this plugin. It has made the arcade experience so much more fun!

**Comment by Boomslangnz** [comment]
Hi

sorry i forgot about this message. Did you sort your issue in the end?

**Comment by camborambo** [comment]
@Boomslangnz No worries at all. I was not able to solve the issue for Initial D Zero. Not sure what is it but the steering wheel center spring just locks up at full force making it extremely stiff to turn. ALl other initial D and mario kart works great. Thank you!

**Comment by bratsrgood** [comment]
I've been playing around with this ffb plugin and it's fun.  Outrun and turbo outrun work perfect for me.  My issue is with cruisn usa and world, once the game starts the center spring tension is too strong, ffb works, but cant figure out how to lower center spring.  I'm starting to think it's the rom itself.  Any ideas

**Comment by Boomslangnz** [comment]
are you using the forced spring effect or without?

**Comment by bratsrgood** [comment]
Tried both ways cruisn works good on track selection and car pick but as
soon as the car starts the wheel gets so hard to turn
