### ISSUE TITLE
Supermodel r839+

### ISSUE THREAD

**Issue by andersstorhaug** [Boomslangnz/FFBArcadePlugin#14]
With the [official builds](https://www.supermodel3.com/Download.html) of Supermodel it seems that r839 broke FFBArcadePlugin support. I can run r838, but r839 with the same configuration crashes with no logs from FFBArcadePlugin (`Logging=1`).

[Relevant SVN r839 commit info](https://sourceforge.net/p/model3emu/code/839/).

I think the reason is that Supermodel r839 has `NET_BOARD = 1` in `Options.inc`. If I include FFB's `ONLY COPY FILE INSIDE THIS FOLDER IF OLDER SUPERMODEL VERSION BEFORE r791\SDL2.dll` then the emulator runs again, and FFBArcadePlugin emits logs (though, I am unable to test functionality at the moment).

**Comment by Boomslangnz** [comment]
Hm ok ill take a look today. Thanks for letting me know

**Comment by Boomslangnz** [comment]
Hi

I just tested here with x64 build on r845 and FFB Arcade Plugin still works fine for me here

**Comment by andersstorhaug** [comment]
Ah, interesting. I think that the builds differ from the forum builds (latest r845) vs the new builds now on https://www.supermodel3.com/Download.html (latest r846). And I suspect the difference is net support? But, I'm not sure.

**Comment by Boomslangnz** [comment]
I downloaded the latest r850 x64 and still works fine

Folder appeared to be missing SDL2.dll however so i copied across from FFB Plugin and worked fine ingame so im closing this as it seems good to me
