### ISSUE TITLE
Graphic decrease when using the plugin

### ISSUE THREAD

**Issue by GiumGium** [Boomslangnz/FFBArcadePlugin#15]
Hello, I have a weird issue with the Ffb plugin. In both games on which I tried it (chaseHQ2 and H2overdrive) the plug-in works perfectly BUT it changes the rendering of the game to something less sharp than before installing the files (I assume it’s coming from the d3d9.dll because when I replace it by the original file the FFB stops working and graphics are sharp again). I’m using latest versions of TP and FFB plugin on an up to date windows10. Thx!!

**Comment by Boomslangnz** [comment]
Uh never heard of this occuring before.

Try rename d3d9.dll to winmm.dll and see if same issue occurs

**Comment by GiumGium** [comment]
Awesome!!! It works, I renamed d3d9.dll in winmm.dll and put back the original d3d9.dll and graphics are sharp again plus the FFB works perfectly. Thanks a million!
