### ISSUE TITLE
PS2 DualShock SCPH-10010

### ISSUE THREAD

**Issue by yepyepyep4711** [Boomslangnz/FFBArcadePlugin#16]
Hello,

I'm using an original PS2 DualShock. Using [these drivers](https://github.com/aitte2/dualshock_driver), I'm able to test rumbling from the game controller settings in windows, and it works. Sadly so far I haven't been able to do the same with this plugin. Tried both GUID with or without the alternate FFB from the test utility without success. What can I do to get to the bottom of this?

EDIT: the end goal is to get this working with Out Run in MAME

**Comment by Boomslangnz** [comment]
Install visual runtime all in one pack

https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/

**Comment by yepyepyep4711** [comment]
> Install visual runtime all in one pack
> 
> https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/

Did that before posting (I read the txt in docs ;) )

**Comment by Boomslangnz** [comment]
Are you still needing help with this? Im afraid PS2 controller may be too old to work with SDL2 which performs Rumble Effects etc

**Comment by Boomslangnz** [comment]
No reply for years, closing.
