### ISSUE TITLE
Not working with Battle Gear 4 Tuned but working with other Teknoparrot games

### ISSUE THREAD

**Issue by teachingtechYT** [Boomslangnz/FFBArcadePlugin#17]
Trying to get ffb working with Battle gear 4 Tuned (v2.08) with Teknoparrot UI (v1.0.0.604).
Ffb is working with Initial D AS 8, Wangan Midnight 5, Sega Rally 3 so I'm confident I'm setting it up correctly.
Wheel is Simagic M10.
d3d9.dll is renamed to winmm.dll as per #15 to avoid a conflict with dgVoodoo, although leaving it with the correct name made no difference.
Is there some particular setting needed for BG4T compared to the others?
Thanks for your great solution.

**Comment by teachingtechYT** [comment]
Here's my log: https://pastebin.com/4qhTrf5F
There is a bit early where it says disabling all ffb effects. Perhaps you can see if that is significant or not.

**Comment by Boomslangnz** [comment]
Hi

just tested on latest Teknoparrot updates and ffb worked fine here. I don't use dgVoodoo however and left plugin named as d3d9.dll. You seem to be recieving values fine but if you are getting no effects then you most likely have conflict somewhere causing issue
