### ISSUE TITLE
Demul plugin not working when running demul via command line/shortcuts

### ISSUE THREAD

**Issue by Linkandzelda** [Boomslangnz/FFBArcadePlugin#18]
I've successfully configured the FFB plugin for demul to play Initial D 1, 2 and 3. When I launch demul by double clicking demul.exe and then select "Load naomi", then select the Initial D games the FFB works as expected.

However when launching demul with a shortcut e.g. `demul.exe -run=naomi -rom=initdexp` the FFB plugin never initialises. I tested this with both windows shortcuts and running directly from the command line, as well as using Launchbox.

**Comment by Boomslangnz** [comment]
Hm ok ill try take a look as soon as i have time

**Comment by Boomslangnz** [comment]
Hi.

just tested here with windows shortcut and ffb worked fine for me

**Comment by Linkandzelda** [comment]
Which version of demul are you using?

**Comment by Boomslangnz** [comment]
tested on 07_180428 which you download from their forum (latest)
