### ISSUE TITLE
Wheel moving left and right on it's on with Initial D Zero/Zero V2

### ISSUE THREAD

**Issue by Linkandzelda** [Boomslangnz/FFBArcadePlugin#19]
I have successfully got Initial D Zero and Zero V2 to launch and play on my machine, however I cannot get proper force feedback to work with my Logitech G29 wheel. During startup when it says "don't touch the wheel", it does random movements left and right at different speeds and continues until it cannot turn any more. After this it stays locked right or left. During the menus, it will move left or right on it's own but much slower. This also happens in races.

During races, there's no center spring effect, and the FFB is nothing but a few jolts and clicks. I'm not familiar with the real arcade feel, but it doesn't feel proper like Initial D 1-3.  Switching Initial D Zero mode to 1 or 2 produces no game FFB. Also selecting to lock the spring, or enable damper, disables all other  game FFB. In order to test this I tested force feedback in the TEST menu and selecting left and right produces nothing.

The Logitech G29 profile I have set to 540 rotation and sensitivity to 100. Without this, I can hardly steer in game.

**Comment by Boomslangnz** [comment]
Please update to latest and try, Initial D FFB was updated recently and this problem should not exist
