### ISSUE TITLE
no FFB with dirt dash when set to deluxe

### ISSUE THREAD

**Issue by Cheesmaker** [Boomslangnz/FFBArcadePlugin#20]
first thanks for all you do,

I've got the chance (or not ) to have an old dirtdash deluxe and a old rave with dead PCB. I'm used to do rewamp with sega model 2,3. So it was great to renew the rave (with arcade crt) but now i'm just near the goal with the dirt dash. I've got all the cabine mouvement (pneumatic command through arduino and mamehooker)  but no FFB. 
When you set the rom in mame in deluxe the log ffb is empty. When i set to standard it's ok but no cabine mouvement obviously.
part of the log in deluxe mode.
"
RunningFFB = (null)
romname = @_Æ
RunningFFB = (null)
romname = dirtdash
RunningFFB = NamcoFFBActive
DLLMAIN ENTERED
process name:
D:\RETROPLAY\mame\groovymame2\mame64.exe
default centering & friction values:
0
0
detaching from process:
D:\RETROPLAY\mame\groovymame2\mame64.exe"

I've read your code but i don't now how to search with this konami game to get the good value in the rom so I can't estimate the 
difficulty. Just tell me what you think about that.

**Comment by Boomslangnz** [comment]
Hey

I can take a look and see whats going on. Should be easy enough to get working i would think

I do pattern scan for those games and it looks like that part is correct still as its going to namco one so surprised ffb gives nothing

**Comment by Boomslangnz** [comment]
Hi, was this fixed yet? I Can't remember :D

**Comment by Cheesmaker** [comment]
Hello Boomslangz,

no, it was not fixed the dirt dash DLX is sleeping :( with no FFB but you've done so much thing...thanks

The rave racer is finished thanks to your job and the dev from NJZ (gamoover) it's almost perfect (and we have the real thing also to compare).

If you can look at this it could be very cool, I can hack the FFB with a DC moto driver BUT another thing, I can acces an another dirt-dash deluxe which is fonctionnal and I want to scan/sniff the serial command to the real ffb board.
I've got the original FFB board (also a Rave Racer FFB board) and the best way is to send directly the serial command to the drive board (but I don't know for the moment the possible pre and post serial command) so if the torque command (or the original string that you parse in your code) can be send also to mamehooker it's very interesting in my case (the same for rave racer). 

The progress with real hardware of all the SEGA racer are impressive and it is a great goal to save the arcade NAMCO with the maximum of original hardware. NAMCO PCB system 22 is practically impossible to fix (specials components ) so in the futur we will have to emulate.
 
I know I ask a lot but don't worry if you can just look of the FFB in dirt dash deluxe mode it's already great.

We don't make money with all this, we are preserving arcade and make free arcade room in hospital.

Other thing i must do a video of a ultime multicab with about 64 rvb outputs and 128 outputs in 2812 with 5ms regeneration....and two active lcd for HID. So a pure DaytonaUSA with no HID in the screen it's the reverse of all we are doing for arcade cab but we can play with all the great stuff that has been done from Saylor Sat, Howard, Retrorepear, Ramjet and a lot of others like You...

I'm using your simtools plug-in (great), I will have to modify the plug-in to hook to "daytona USA saturn adds" because of the great Saylor-SAT live Lan.

 

Vincent ROY
RETROPLAY 44
www.retroplay.fr










----- Mail original -----
De: "Boomslangnz" ***@***.***>
À: "Boomslangnz/FFBArcadePlugin" ***@***.***>
Cc: "Cheesmaker" ***@***.***>, "Author" ***@***.***>
Envoyé: Vendredi 10 Juin 2022 13:04:38
Objet: Re: [Boomslangnz/FFBArcadePlugin] no FFB with dirt dash when set to deluxe (Issue #20)





Hi, was this fixed yet? I Can't remember :D

**Comment by Boomslangnz** [comment]
hm I can't seem to play dirt dash anymore on latest mame

Loads up but just has black screen but turns green after a bit... :(

**Comment by Boomslangnz** [comment]
Nevermind, turns out I needed dirtdasha.zip which is working instead of dirtdash.zip

anyway made some tweaks on namco FFB and seems to work fine for both standard or deluxe now. May need to restart game after switching machine over potentially

https://mega.nz/file/cJdhWCoY#BDnIitFf6-2ZVml1R8Sk9YCSrRWsoyl4v34Wmgs39rI

**Comment by Cheesmaker** [comment]
wow !

thanks for the great job, just tested with dirtdash.zip with mame 0.226 and .... it works well!
I send you video of test very soon !
