### ISSUE TITLE
Logitecg G29 WMMT6 center force

### ISSUE THREAD

**Issue by Revenger** [Boomslangnz/FFBArcadePlugin#22]
There seems to be a force feedback bug with WMMT6 with the G29 it is loose on the center force for about 45 degrees and weak for the rest of the turning despite having a center force applied in Ghub toggling the use centering spring force button brings the centre force back so the whole wheel has force but you have to do it once the race starts.

Reloading the game you need to apply the centering spring force button every first race.

Doesn't matter if the use center force button in Ghubis checked or unchecked just toggling the option turns it on.
Have a dedicated profile for WMMT6 in Ghub.

Mby I am not noticing a option in the FFB plugin or something.
May affect other games don't know.

**Comment by Boomslangnz** [comment]
I don't understand exactly, this doesn't occur for me on Thrustmaster wheel so perhaps its Logitech issue

**Comment by Revenger** [comment]
I'll need to check the plugins again sometime and see if it persists.
The way it was yea seems mostly a logitech thing with how the plugin was working.
