### ISSUE TITLE
FFBArcadePlugin cann't catch the InitialD8 CHT redumped

### ISSUE THREAD

**Issue by tkp206093** [Boomslangnz/FFBArcadePlugin#25]
[InitialD8_GLW_RE_SBZZ_redumped_.zip](https://github.com/Boomslangnz/FFBArcadePlugin/files/9184895/InitialD8_GLW_RE_SBZZ_redumped_.zip)
I change the default redumped to CHT redumped
and FFBArcadePlugin not work

I test the FFBArcadePlugin in InitialD Zore v2 is working

**Comment by Boomslangnz** [comment]
What is CHT redumped?  

FFB Plugin hooks the application on launch and ID8 always calls Dinput8.dll so don't see how thats possible.

However you can rename it to d3d9, xinput1_3, winmm, dinput, dinput8, opengl32 or d3d11 depending on application etc

**Comment by tkp206093** [comment]
change the InitialD8 language to traditional Chinese.

**Comment by Boomslangnz** [comment]
Does it change ini stuff to Chinese?

I read all my info from the ini so perhaps it can’t read it after making that change

**Comment by tkp206093** [comment]
You said what .ini
db_sv.ini
mxGetHwInfo.ini
initialD.ini
renderer.ini

this CHT redumped not change the .ini
but alll tips and operations For example, the waiting interface at the beginning is also converted into Chinese

**Comment by tkp206093** [comment]
[FFBlog.txt](https://github.com/Boomslangnz/FFBArcadePlugin/files/10956394/FFBlog.txt)
Oh now InitialD Zore v2 also not work
I thank FFBArcadePlugin not support the new G HUB racing wheel drivers
C:\ProgramData\LGHUB\depots\170315\driver_hid_virtual

In Project CARS 3, Assetto Corsa Competizione is ok work

IN FFBPluginGUI test is work

b ut in the game is not work

**Comment by tkp206093** [comment]
> 什麼是CHT轉儲？
> 
> FFB 外掛程式在啟動時挂鉤應用程式，ID8 總是調用 Dinput8.dll所以看不到這是怎麼回事。
> 
> 但是，您可以將其重命名為d3d9，xinput1_3，winmm，dinput，dinput8，opengl32或d3d11，具體取決於應用程式等

[FFBlog.txt](https://github.com/Boomslangnz/FFBArcadePlugin/files/11158106/FFBlog.txt)

**Comment by Boomslangnz** [comment]
latest update works with latest logitech driver, tested it myself
