### ISSUE TITLE
OutRun 2 SP SDX don't run with opengl32.dll in folder TP/TP (teknoparrot 1.0.0.804) (FFB 2.0.0.14)

### ISSUE THREAD

**Issue by saiyanvip** [Boomslangnz/FFBArcadePlugin#26]
Hi,

OutRun 2 SP SDX don't run with opengl32.dll in folder TP/TP (teknoparrot 1.0.0.804) FFB (2.0.0.14)

Crash after the box dialog teknoparrot.

Thx

**Comment by saiyanvip** [comment]
> Hi,
> 
> OutRun 2 SP SDX don't run with opengl32.dll in folder TP/TP (teknoparrot 1.0.0.804) FFB (2.0.0.14)
> 
> Crash after the box dialog teknoparrot.
> 
> Thx

I just found a solution by searching on a forum... you have to use "sdl2.dll v2.0.9.0 and opengl32.dll v2.0.0.4"!

Is there a solution for a future version? or the problem is related to teknoparrot?

**Comment by OutrunK1** [comment]
hey my Outrun is still crashing after the box dialog. So did you grab files from two different versions? Did you copy both of them to both the jennifer file and teknoparrot or just teknoparrot. Do you think you can link the forum you found the answer on?
thanks

**Comment by saiyanvip** [comment]
> hey my Outrun is still crashing after the box dialog. So did you grab files from two different versions? Did you copy both of them to both the jennifer file and teknoparrot or just teknoparrot. Do you think you can link the forum you found the answer on? thanks

Hi, dont remember... for forum maybe here http://forum.arcadecontrols.com/index.php?topic=157734.240 or emuline but the forum is down.

**Comment by Boomslangnz** [comment]
Thanks for info
