### ISSUE TITLE
Latest GHUB Update Killed FFB for my G920

### ISSUE THREAD

**Issue by hellshakeyan0** [Boomslangnz/FFBArcadePlugin#28]
No matter which version of GHUB I install my G920 won't function with any FFB Arcade Plugins now. Happened after last update, and no amount of deleting drivers and installing other software has helped me. I've tried LGS as well.

**Comment by Boomslangnz** [comment]
There was a big Logitech bug which killed FFB working, eventually a Logitech driver was released to fix and hopefully works fine now as it does for others
