### ISSUE TITLE
"External DAT View" Option unavailable in MAME while FFBArcadePlugin is installed

### ISSUE THREAD

**Issue by CBusse** [Boomslangnz/FFBArcadePlugin#30]
I was just wondering why i could not see the info from mameinfo.dat and history.xml anymore when I realized that they disappeared after I installed FFBArcadePlugin here - is this a bug or a known behaviour?
Removing the plugin .dll's let them come up again here.

Can they be enabled again with the plugin installed somehow, or is there a serious reason to disable those with the plugin enabled?

**Comment by Boomslangnz** [comment]
Tbh i have no idea what those things even are. I dont see why they wouldnt work fine with FFB Plugin

**Comment by CBusse** [comment]
well, somehow it works again now, but it  is some strange behavior.

the option External DAT View shows contents from mameinfo.dat and history.xml for the running machine (mameinfo.dat delivers info about the driver history itself, at which mame version it was introduced, major changes etc, history.xml show interesting knowledge around the running machine and also a list if it is a game series about other parts)

https://mameinfo.mameworld.info/  - just extract mameinfo.dat into the mame root dir - will be picked up on next start

https://www.arcade-history.com/index.php?page=download - extract into <mameroot>\history   - will be picked up on next start too

**Comment by CBusse** [comment]
will update here if i find out more why it sometimes shows and sometimes not with ffbarcadeplugin installed
