### ISSUE TITLE
Debug flavor crashes MAME on launch

### ISSUE THREAD

**Issue by ckeisc** [Boomslangnz/FFBArcadePlugin#34]
Release flavor works. Don't know enough about the code base to figure out why just yet. Reporting it first in case it's new and not known yet.

-----------------------------------------------------
Exception at EIP=00007ff62dbf8294 (not found): ACCESS VIOLATION
While attempting to read memory at 000000007a8f9438
-----------------------------------------------------
RAX=00007ff62dbf8290 RBX=0000000000000004 RCX=000000e07a8f8e70 RDX=000000007a8f9430
RSI=00007ff62dbf8290 RDI=000002752dc1cab8 RBP=000000007a8f9430 RSP=000000e07a8f8e00
 R8=0000000000000001  R9=0000000000000059 R10=0000000000000008 R11=000000e07a8f8d50
R12=000000e07a8ff9d0 R13=000000e07a8f95a0 R14=000000e07a8f9588 R15=000002752cd3d380
-----------------------------------------------------
Stack crawl:
  000000e07a8f8e20: 00007ff62dbf8294 (not found)
  000000e07a8f92e0: 00007ffc47852687 (DirectInput8Create+0x0457)
  000000e07a8f93e0: 00007ffc0e5263f0 (DirectInputDeviceWrapper::EnumObjects+0x00a0, C:\Users\admin\Downloads\FFBArcadePlugin-2.0.0.14\IDirectInputDevice.cpp:77)
  000000e07a8f94a0: 00007ff62dbf23c1 (not found)
  000000e07a8f94d0: 00007ff62b5c305c (not found)
  000000e07a8f9630: 00007ff62b5c4c05 (not found)
  000000e07a8f9910: 00007ff627ecf46a (not found)
  000000e07a8f9a30: 00007ff62813cfd3 (not found)
  000000e07a8f9b90: 00007ff62813f471 (not found)
  000000e07a8ff200: 00007ff62b5d7c7b (not found)
  000000e07a8ff5e0: 00007ff62de8f7ef (not found)
  000000e07a8ff8a0: 00007ff62de8fdfd (not found)
  000000e07a8ff900: 00007ff62b5d4ee9 (not found)
  000000e07a8ffcd0: 00007ff62ef28027 (not found)
  000000e07a8ffda0: 00007ff6239c13b1 (not found)
  000000e07a8ffdd0: 00007ff6239c14e6 (not found)
  000000e07a8ffe00: 00007ffc656b7034 (BaseThreadInitThunk+0x0014)
  000000e07a8ffe80: 00007ffc659226a1 (RtlUserThreadStart+0x0021)

**Comment by Boomslangnz** [comment]
Sorry I need more info to understand what issue is
