### ISSUE TITLE
Daytona Championship USA (aka Daytona 3) Unstable with FFB Arcade plugin

### ISSUE THREAD

**Issue by bunjun8566** [Boomslangnz/FFBArcadePlugin#35]
I am using TeknoParrotUi 1.0.0.838 and FFBPlugin( SDL2.dll 2.0.0.22.0,  MetroFramework.dll 1.4.0.0, dinput8.dll 2.0.0.14)
Daytona Championship USA (Daytona.exe) timestamp is 2018/01/13.
There are 3 problems, one is Car Selection/Course Selection, sometimes game gets hang up if FFB is enabled.
another one is rampage of steering wheel between goal and name entry.
Last one is game getting hang up when return to white screen (usually Press start is blinking)

Steering wheel is thrustmaster T300RS GT edition.

How can proceed troubleshooting ?

Other game (SWDC)  works ok with FFB.

**Comment by Boomslangnz** [comment]
Perhaps you need to rename the plugin to d3d11.dll or winmm.dll

Ive never heard these issues from any other user before however

**Comment by diegoviso** [comment]
@bunjun8566 - You may want to try swapping between USB ports (EG USB 2 / 3) to see if it makes a difference. I've seen odd issues with input delay and wheel responding strangely with FFB on... Wheel is ok with FFB off. Problem went away when I used a different usb port.

**Comment by Boomslangnz** [comment]
latest update appears to have none of these issues
