### ISSUE TITLE
Rave Racer rumble effects

### ISSUE THREAD

**Issue by ckeisc** [Boomslangnz/FFBArcadePlugin#36]
@Boomslangnz - is there any tutorial on how to add / improve support for the effects in games? I replaced Arcade1Up's proprietary emulator that has rumble support of its own with MAME + FFB Arcade Plugin and I think a few rumble effects are missing - like when the car occasionally goes off road and slam back down to the road, there was a strong rumble on A1U's emulator but nothing in particular with FFB Arcade Plugin. I turned on logging and saw that maybe the rumble value (value that shows in "got value" in log) 1 and 2 might be used as some sort of control codes for special events since they were too weak to be felt as normal rumble events. And code 123 seems to be sent constantly even after game over, so could this be some sort of event to reset rumble?

How did you reverse engineer the rumble support in these games in general, and anything to share in improving Rave Racer's mapping / implementation? The code has a giant switch statement on all possible rumble values most likely to handle the presence of some of these magic control values, but nothing seems to be hooked up other than rumble when turning left and right.

**Comment by Boomslangnz** [comment]
Sorry for late response,

I don't know what Arcade1Up is sorry, I just analyzed the values and attempted to create the FFB based on that. I'm not sure if the feeling of rumble would be that strong on controller, however with wheel there is a strong effect when car slams back down on road after jumps etc

It could be improved :)
