### ISSUE TITLE
No force feedback on one G920

### ISSUE THREAD

**Issue by pixelplacement** [Boomslangnz/FFBArcadePlugin#37]
I have two identical driving simulator rigs, each have identical PCs, G920s, shifters, and USB handbrakes.  One gets force feedback fine and the other doesn't. Thoughts on what I can test?

**Comment by Boomslangnz** [comment]
https://www.youtube.com/watch?v=82oGDqxAnGk

try these steps

**Comment by pixelplacement** [comment]
I will, thank you. I wanted to add that force feedback works on both in all Steam games but not from this plugin. I will circle back after I try the video. Thank you!

**Comment by pixelplacement** [comment]
Tried the video's suggestions; still no luck. Thoughts?

**Comment by Boomslangnz** [comment]
Sorry for late response, have you had any luck getting it working?

**Comment by pixelplacement** [comment]
Thanks for following up. I ended up switching over to Thrustmasters. I was to get it working with the Logitech wheels. On Jan 21, 2023 1:27 AM, Boomslangnz ***@***.***> wrote:
Sorry for late response, have you had any luck getting it working?
