### ISSUE TITLE
Integration with SimRacingStudio API

### ISSUE THREAD

**Issue by marcelomanzo** [Boomslangnz/FFBArcadePlugin#4]
Hi, 
I'm wondering if would be possible to integrate the BBAArcadePlugin with the SimRacingStudio Api:
https://gitlab.com/simracingstudio/srsapi

A noticed in code you capture values for speed and gear for certain game, and that would be extremely helpful to add fun for my motion simulator with wind sim and shakers.

**Comment by Boomslangnz** [comment]
You could certainly do that but currently it's set just to perform force feedback or rumble effects via SDL2. How would you trigger the wind and bass shakers?

**Comment by marcelomanzo** [comment]
If you look into the API documentation, it expects some dashboard and telemetry data from the vehicle:
https://gitlab.com/simracingstudio/srsapi

To control the speed it uses the speed of the vehicle
To control the shakers, it uses the gear, rpm and g-forces (lateral, longitudinal and vertical acceleration)
To control the motion platform, yaw, roll pitch + g-forces.
There are also terrain and suspension, that makes the effects of shakers even more realistics.
