### ISSUE TITLE
Logitech g920 not working with plugin

### ISSUE THREAD

**Issue by FoxBox77** [Boomslangnz/FFBArcadePlugin#40]
G920 no longer working in FFb plugin - test mode in the plugin shows an error, "Does not support rumble", and none of the other feedback test buttons work. I have tried uninstalling GHub, restarting  and installing the older Logitech Gaming software - no change. I have used different USB ports and disconnected other devices - no change. The G920 works normally with all other software.

**Comment by Boomslangnz** [comment]
Sorry for late response, Logitech is a constant issue for some reason, please come to TeknoParrot discord and we can try help get this sorted
