### ISSUE TITLE
Problem with flycast

### ISSUE THREAD

**Issue by faluki1983** [Boomslangnz/FFBArcadePlugin#41]
I have problems every time I install the FFBPlugin on flycast, the winmm.dll file crashes the controls (xbox controller) on the emulator and I can't play.

**Comment by Boomslangnz** [comment]
Does this still occur? I have no such issue and done a bunch of work on Flycast recently

**Comment by baritonomarchetto** [comment]
I have tested the latest release (031) and, yes, xbox controller (in my specific case an arduino emulating an xbox controller) is no more responsive in flycast if the plugin is active

**Comment by Boomslangnz** [comment]
sorry for late reply on this again, i did look into this but couldn't resolve the issue at the time (March 14th) BUT it does seem its fixed on latest FFB Plugin version as ive just tested it out again today, if i tried old version from march 14th then it does indeed stop inputs

Seems i fixed it somewhere along the way :)
