### ISSUE TITLE
FFBArcadePlugin can not work on my computer

### ISSUE THREAD

**Issue by ARX233** [Boomslangnz/FFBArcadePlugin#42]
Sorry to bother you.I set it up according to the prompt of the plug-in.But it can't work in a right way.The game I played is WanganMidnight 5 and 5DX+, they all can't work in these games.And I checked my windows C++ runtime and DirectX. It seems no problem. I can't think what problem lead that FFB can't work.
My computer is dell g15,and system is Windows 11.And the steering wheel is Tumaster t300RS.
sorry my English is poor.

**Comment by Chispes** [comment]
I have the same problem, I have tried everything, but I can't get any FFB game to work. In test mode the wheel works correctly, but once the game starts there is no ffb.

**Comment by Boomslangnz** [comment]
> I have the same problem, I have tried everything, but I can't get any FFB game to work. In test mode the wheel works correctly, but once the game starts there is no ffb.

Hm what game are you attempting on?

**Comment by Chispes** [comment]
i have tried Wangan Midnight Maximum Tune 6, sega rally 3, outrun 2sp. i have even formatted the computer to see if it would work and there is no way to make it work. i have tried several games, i have changed cables, i have tried on usb2, usb3, etc. The steering wheel is a ts-xw

**Comment by Boomslangnz** [comment]
I don't know, I have T300RS wheel here and works without issue. Could you please update visual runtime files to latest available in one of those all in one packs to see if any change? Otherwise you may need to come to TeknoParrot discord and chat with us to try solve issue more directly eg Teamviewer

**Comment by Boomslangnz** [comment]
Recommend updating to latest version, closing this due to no reply
