### ISSUE TITLE
some problem on WMMT6R by Moza R5

### ISSUE THREAD

**Issue by AlexFugui** [Boomslangnz/FFBArcadePlugin#43]
@Boomslangnz  
use moza R5
and play wangan 6R

When I select moza R5 in FFB to play the game
Will crash at the beginning of the game
Now,the crash problem has been solved
However, there will still be crashes during the game, and there will be no crashes when FFB is not used
How to troubleshoot this problem?

[FFBlog.txt](https://github.com/Boomslangnz/FFBArcadePlugin/files/10949981/FFBlog.txt)
[FFBlog.txt](https://github.com/Boomslangnz/FFBArcadePlugin/files/10950021/FFBlog.txt)
This is a crashed ffblog

and this is my TeknoParrotUi version 1.0.0.0
There are customized content specially made for wmmt6R
![image](https://user-images.githubusercontent.com/22453816/224525648-a08de955-f0ed-4bbf-be52-0e7d4278a611.png)

**Comment by AlexFugui** [comment]
The problem has been solved

Because wangan6R requires the administrator to start TeknoParrotUi

So you need to set TeknoParrotUi, FFBPluginGUI and wmn6r.exe to start for the administrator

Now you can play normally and give strong feedback



PS: It is best to install Visual Runtime Files

https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/

**Comment by AlexFugui** [comment]
Take a look at the project code
This problem seems to have something to do with TeknoParrot
Is there any way to continue troubleshooting?

**Comment by Boomslangnz** [comment]
? No one else has this issue across loads of people running ffb plugin on any games , I see no reason it would randomly crash during gameplay.

perhaps just rename d3d11 to winmm and try

**Comment by AlexFugui** [comment]
> ? No one else has this issue across loads of people running ffb plugin on any games , I see no reason it would randomly crash during gameplay.
> 
> perhaps just rename d3d11 to winmm and try

ok
rename d3d11 file in ffb?
I try now

crashes frequently occur today
it is currently suspected that it is one of the graphics cards/TekonoParrot/ffb
but if the selected device in the ffb is turned off, it will not crash
there is no clue about troubleshooting :(

**Comment by Boomslangnz** [comment]
The ffb plugin file you copied to game folder is called d3d11.dll. Rename this to winmm.dll

**Comment by AlexFugui** [comment]
> The ffb plugin file you copied to game folder is called d3d11.dll. Rename this to winmm.dll

ok I restest thk
I will give feedback if there is any new situation

**Comment by AlexFugui** [comment]
> The ffb plugin file you copied to game folder is called d3d11.dll. Rename this to winmm.dll

The force feedback disappears after renaming  :(
[FFBlog.txt](https://github.com/Boomslangnz/FFBArcadePlugin/files/10950364/FFBlog.txt)

**Comment by Boomslangnz** [comment]
Could you try an older version please, test 2.0.0.15 or so

we are investigating but helps with more testers.

someone else has same issue

**Comment by Boomslangnz** [comment]
https://mega.nz/file/VINkjabD#XaI-a3tvByA7dhsvEb4_Joldr_h3svCyhXul3LxYd-A

Please download this and try out to see if it fixes your crashes

**Comment by AlexFugui** [comment]
> > Could you try an older version please, test 2.0.0.15 or so
> > we are investigating but helps with more testers.
> > someone else has same issue
> 
> About 30 games have been played with version 2.0.0.15 without crash
> 
> About 20 games were played with version 2.0.0.25 without crashing, but once the game ended and lost the feedback of the return force, until the next game began to return to normal

I feel 2.0.0.25 version force feedback is more detailed

**Comment by Boomslangnz** [comment]
Did you test the new version i sent via mega link?

**Comment by AlexFugui** [comment]
> Did you test the new version i sent via mega link?

yes i did

**Comment by Boomslangnz** [comment]
ok and no crash?

**Comment by AlexFugui** [comment]
> ok and no crash?

yeah new version is ok
but once the game ended and lost the feedback of the return force, until the next game began to return to normal

**Comment by Boomslangnz** [comment]
I don't understand sorry, lost the feedback of the return force and until next game began to return to normal

Could you explain in another way please?

**Comment by AlexFugui** [comment]
When I finish a game, when I select the map interface, there is no feedback on the back force, until the new game starts and the countdown ends, and then returns to normal

Sry, my English is not very good :(

**Comment by Boomslangnz** [comment]
I don't think there is meant to be any feedback when you are not racing

**Comment by AlexFugui** [comment]
> I don't think there is meant to be any feedback when you are not racing

But when you select a map, wheel will automatically return to the center
use new version only once

**Comment by AlexFugui** [comment]
game crashed again today
restarting the computer will not recover
Use 2.0.25test/2.0.15/2.0.25 will also crash
but it will not crash when the steering wheel is powered off or the USB is disconnected
How to troubleshoot this problem?
[FFBlog.txt](https://github.com/Boomslangnz/FFBArcadePlugin/files/10964076/FFBlog.txt)

**Comment by AlexFugui** [comment]
this bug that the game started can be reproduced
game will crash when starting the Hurong Internet Security or 360 Security software
if close security before starting the game, it will not crash
has been tested on 5 computers
test version 2.0.0.25

**Comment by Boomslangnz** [comment]
well you need to set exclusion on game folder then
