### ISSUE TITLE
I can't work ForceFeedback on InitialD titles (teknoparrot)

### ISSUE THREAD

**Issue by mame-rr-player001** [Boomslangnz/FFBArcadePlugin#45]
I can't work ForceFeedback on 
InitialD titles (teknoparrot)

I put FFBArcadePlugin files on the directory as below
(where exists "Game Executable" file).

What should I do?

Are there any solution?

・InitialD: Arcade Stage 4
\Initial D 4 Export
\Initial D 4 Japanese

・InitialD: Arcade Stage 5
\Initial D 5 Export
\Initial D 5 Japanese

・InitialD: Arcade Stage 6 Double Ace
\Initial D Arcade Stage 6 AA

・InitialD: Arcade Stage 7 Double Ace Cross
\Initial D Arcade Stage 7 AA

・InitialD: Arcade Stage 8 Infinity
\Initial D Arcade Stage 8 Infinity

・InitialD: Arcade Stage Zero
\Initial D Arcade Stage Zero\app\package

・InitialD: Arcade Stage Zero Ver.2
\Initial D Arcade Stage Zero v2\package

**Comment by Boomslangnz** [comment]
Yea you need to load FFBPlugin.exe and click on Setup Help and follow all instructions carefully

**Comment by mame-rr-player001** [comment]
Thanks for you to let me know the solution.
As you say, I can setup and be able to play 
TeknoParrot Drive Games with FFB.
