### ISSUE TITLE
Update missleading MAME instructions

### ISSUE THREAD

**Issue by vaccinemedia** [Boomslangnz/FFBArcadePlugin#46]
I recently followed the instructions for MAME which led to me losing several hours and almost uninstaling the drivers for my steering wheel and downloading unnecessary versions of MAME in order to get the plugin working. It's all to do with 2 things:

1. The instructions state to create a file called mame.ini with some text which needs to be copiedand pasted into it
2. Windows creates text files with .txt as the file extensiion by default if you do it from thr file explorer

I followed the instructons, created a file called (what I thought was) mame.ini and pasted in the text. This did not enable FFB. After much forum searching and thinking that there mut be something wrong with my drivers due to a Reddit rabbithole  went down I finally decided to check the filename of the file I was asked to create which was in fact mame.ini.txt

I went to rename it and was told I can't rename it to mame.ini as a file with that name already exists! On inspecting that file I can see that MAME has it's own mame.ini file full of settings and all I needed to do was change the value of one of them.

So please change the instructions from asking the user to create a file called mame.ini to asking them to change the appropriate setting as there will be end users out there who will not notice that Windows has created a file called mame.ini.txt and more importantly they dont need to do so anyway as it aleady exists. Just tell them they need to edit the mame.ini file instead.

**Comment by Boomslangnz** [comment]
Ok thanks, will look at making readme more clear :)
