### ISSUE TITLE
FFB does not work with Supermodel

### ISSUE THREAD

**Issue by mlnlbrt** [Boomslangnz/FFBArcadePlugin#5]
I can't get FFBArcadePlugin to work with Supermodel emu games. It works fine with Virtua Racing (latest MAME) and Outrun 2 (TeknoParrot), but no luck with Supermodel. Native FFB in Supermodel is also fine.

I've tried Scud Race with 32-bit Supermodel and Sega Rally 2 with 64-bit Supermodel. Test Force Feedback in FFBPluginGui works okay. Changing cabinet types does not help too. 

My hardware is Logitech G29 and software is Win 8.1 Pro x64 with Logitech Gaming Software 9.02.65.

Here are logs:

Scud Race error.log: 
[error.log](https://github.com/Boomslangnz/FFBArcadePlugin/files/4505112/error.log)

Scud Race FFBlog.txt:
[FFBlog.txt](https://github.com/Boomslangnz/FFBArcadePlugin/files/4505114/FFBlog.txt)

Sega Rally 2 error.log:
[error.log](https://github.com/Boomslangnz/FFBArcadePlugin/files/4505118/error.log)

Sega Rally 2 FFBlog.txt:
[FFBlog.txt](https://github.com/Boomslangnz/FFBArcadePlugin/files/4505121/FFBlog.txt)

**Comment by Boomslangnz** [comment]
You need to run supermodel roms with the shortcut -outputs=win and also disable Supermodel built in FFB. Ensure all files are in supermodel emulator folder

**Comment by mlnlbrt** [comment]
1. I run supermodel with `-outputs=win`, see error.log file:
`Started as:`
`argv[0] = C:\Arcade\model3\srally2\Supermodel779.exe`
`argv[1] = srally2.zip`
`argv[2] = -res=1920,1080`
`argv[3] = -fullscreen`
`argv[4] = -wide-screen`
`argv[5] = -outputs=win`

2. Supermodel builtin FFB is disabled, see error.log file:
`Runtime configuration:`
`ForceFeedback=0`

3. All files are in place.

**Comment by Boomslangnz** [comment]
What is Px32.exe?

That is what is being hooked instead of Supermodel.exe

**Comment by Boomslangnz** [comment]
Oh sorry lol Stupid phone format showed that bit by itself

**Comment by mlnlbrt** [comment]
`Supermodel789SCSPx32.exe` is the name of Supermodel executable I am using.

Does FFBArcadePlugin require a fixed name of Supermodel executable (Supermodel.exe)?

**Comment by Boomslangnz** [comment]
No

**Comment by mlnlbrt** [comment]
Is there any way to get more verbose logs to help you find out what is going on?

**Comment by Boomslangnz** [comment]
Not quite sure problem yet, but I just downloaded fresh Supermodel-r787 and tested both x64 and x86 versions and both worked fine with FFB Arcade Plugin v1.7b 

Could you try a fresh build and just make a shortcut and just make like target

"C:\SupermodelEmulator\Supermodel.exe" srally2.zip -outputs=win

and see if its working then? I haven't even touched Supermodel.ini at all and I remember someone having an issue with it previously

**Comment by mlnlbrt** [comment]
I tried it on a fresh build and it was working (Sega Rally 2 with 64-bit Supermodel r779), however after changing some options in FFBGui it stopped working again. Even copying FFBArcadePlugin files over didn't help. Then I tried it one more time from the very beginning and it worked to, even after reboot.

Something random is happening here and it seems to be specific to Supermodel. My windows install is as minimal as it can be, just gpu drivers, directx files, logitech software and a few emulators. The only suspect is logitech software, but I don't have any problems with other emus (MAME, model2emu, teknoparrot).

**Comment by Boomslangnz** [comment]
Strange, I've never had issues with it not working like that.

I rememeber someone having issues with the -outputs=win part being in supermodel.ini before and it not working for some reason which is why I prefer to have it in bat/shortcut. I dont know if that really matters though

**Comment by Boomslangnz** [comment]
Have you solved this issue?

**Comment by mlnlbrt** [comment]
Nope, I gave up and just use Supermodel built-in FFB.
