### ISSUE TITLE
FFB Arcade Plugin T300RS GT support issues

### ISSUE THREAD

**Issue by marukochinn** [Boomslangnz/FFBArcadePlugin#52]
Just found out some games eg. WMMT5/6/6R Sega Rally 3 FFB is not working when using lastest driver ( 2023_TTRS_1, 2023_TTRS_3 ) when I installed back the old driver ( 2021_TTRS_1 ) FFB started again... I hope it can help users who use thrustmaster.

https://www.reddit.com/r/Thrustmaster/comments/p67ywg/do_not_update_t300_drivers/

**Comment by Boomslangnz** [comment]
Hello, latest version should work fine and does here, please read recent update notes for any changes that may help too

**Comment by bluejaye** [comment]
@Boomslangnz 

it **never works** even with the latest version in 2025. 
Are you able to review and check it out please.
