### ISSUE TITLE
ForceSpringStrength does nothing when MaxForceDaytona2 is set to 0

### ISSUE THREAD

**Issue by ksdomino** [Boomslangnz/FFBArcadePlugin#55]
I just want to have spring centering without any additional effects (like sine or friction effects).

its currently not possible to have Spring Centering without having all the effects so:
Setting MaxForceDaytona2 to (reduce friction, sine, etc to) 0 means :
ForceSpringCentering: 70 has no effect because MaxForceDaytona is overriding ForceSpringCentering (setting it to 0).

it's fine ONLY WHEN maxForceDaytona2 is greater than ForcesSpringCentering but in that case it's impossible to have spring centering without getting all the other effects.
 
Separating the 2 settings properly will allows users to set spring centering as needed and force effects (sine, friction) separately as needed (I'm sure this was probably the intention in the beginning hence having 2 settings but it's broken right now).

Thanks.

Setup: Logitech G29 Wheel, supermodel emulator, daytona 2

**Comment by Boomslangnz** [comment]
Hi, just added spring plugin to latest version

Thanks!

**Comment by ksdomino** [comment]
Problem still persists:
(just waiting for youtube vid to finish processing and I'll post a link here)
anyway here's my ini settings:
EnableForceSpringEffectDaytona2=1, ForceSpringStrengthDaytona2=78
MinForceDaytona2=0, MaxForceDaytona2=80
I've zeroed: EnableDamperDaytona2, EnableFFBStrengthDynamicAdjustment, DefaultCentering,, DefaultFriction
(full ini at : https://justpaste.it/bmv16
with that I get good spring but also unwanted force feedback effects.
2 min youtube vid link: https://www.youtube.com/watch?v=J20mbx1V7NU

**Comment by ksdomino** [comment]
Only missing the ability add a small amount of FFB now as the spring-only effects work perfectly. 
Thanks so much!
Maybe in a future update it will be possible to have control over both (spring effect and FFB) but I'm very grateful for the update!
