### ISSUE TITLE
WE hope to add support for WMMT6RR and Initial D Arcade Stage games.

### ISSUE THREAD

**Issue by AlexFugui** [Boomslangnz/FFBArcadePlugin#57]
Currently, the 6RR game comes with a built-in Xinput
and we hope to add sup for Initial D Arcade game
and I have Initial D Arcade game files , If you need it, I can provide game files for you to use
: )

**Comment by camborambo** [comment]
Initial D The Arcade (SDGT 1.50.00) FFB support would be greatly appreciated. The game is working with segatools and aime server support now. Just missing that FFB for the full arcade experience.

**Comment by jaoxford** [comment]
> Initial D The Arcade (SDGT 1.50.00) FFB support would be greatly appreciated. The game is working with segatools and aime server support now. Just missing that FFB for the full arcade experience.

Slightly unrelated to the issue at hand. I didn't realise Initial D Arcade was available for emulation? Could you share where to find it / how to get it configured? 

Thanks!

**Comment by Boomslangnz** [comment]
not in plans at the moment
