### ISSUE TITLE
Can we added supported wheels to the Readme?

### ISSUE THREAD

**Issue by Lazzarus** [Boomslangnz/FFBArcadePlugin#59]
Can we add a list of wheels which are known to work with the plugin to the read me or expand the read me to cover what should work?

I’m having trouble finding out what wheels are supported. I’m looking to buy a wheel for my arcade cab and this is a plugin is a must so I want to buy a wheel which is known to work with it. 

The Direct drive wheels have come down in price massively in the last year or so like the  mozaracing bundle or cammusracing but if they don’t work I’ll stick to Logitech or Thrustmaster.

**Comment by Boomslangnz** [comment]
It should work with any wheel really, we use SDL2 to perform the ffb effects so you could check if it works with SDL2 

I have a direct drive wheel at home and it worked fine with FFB Plugin

**Comment by Lazzarus** [comment]
That’s great. Thanks for answering so quickly.
