### ISSUE TITLE
Windows XP compatibility?

### ISSUE THREAD

**Issue by baritonomarchetto** [Boomslangnz/FFBArcadePlugin#6]
Not sure if it's strictly a source compile "issue", but the plugin exe is a x64 application: would it be possible to have a x86 version?
:)

**Comment by Boomslangnz** [comment]
?

The GUI exe is only 64bit for 64bit applications, otherwise I use the x86 version

Unless Ive got something wrong

**Comment by baritonomarchetto** [comment]
I tried the version in the model 2 emulator folder (for model 2 emulator, obviously)

**Comment by Boomslangnz** [comment]
Just checked and the GUI in M2 Emulator folder with FFB Arcade Plugin v1.7b is x86 version

Yes, M2Emulator is 32bit but that doesn't mean x64 won't work on Windows XP depending on the game exe is all. I use 32bit SDL.dll and 32bit exe etc with 32bit applications and 64bit when 64bit applications

**Comment by baritonomarchetto** [comment]
Ok, thanks. I will try to dig more into that "not valid win32 application" error I get, maybe something wrong on my side.

**Comment by Boomslangnz** [comment]
FYI if it won't work on XP for whatever reason. You don't actually require GUI to use FFB Plugin

Just Enable Logging in ini and launch game eg Daytona USA and play for a few seconds then exit

Check FFBLog.txt and will tell you device GUID etc and put that into FFBPlugin.ini and you can modify any other settings in FFBPlugin.ini too

FFBPluginGUI.exe only reads/writes to FFBPlugin.ini anyway

**Comment by baritonomarchetto** [comment]
Thank you for the hint!
I am used to mamehooker, but only recently had the opportunity to play with tour toy ;)

**Comment by baritonomarchetto** [comment]
A direct ini modification worked for me. Thanks!
