### ISSUE TITLE
WMMT 3DX+ FFB please be the  in next update 

### ISSUE THREAD

**Issue by pongpongjin** [Boomslangnz/FFBArcadePlugin#60]
and D The Arcade FFB  thanks

**Comment by pongpongjin** [comment]
@Boomslangnz  thanks bro

**Comment by Boomslangnz** [comment]
WMMT3DX + already supported, just use the WMMT3 plugin

**Comment by pongpongjin** [comment]
> WMMT3DX + already supported, just use the WMMT3 plugin

Place the files in to wmmt3dx+ folder  not working , is there any more instruction

**Comment by pongpongjin** [comment]
both wmmt3dx+or WMMT3 plugin not working during game, @Boomslangnz

**Comment by Boomslangnz** [comment]
yes, you are not installing as per instructions 

opengl32.dll & SDL2.dll to TeknoParrot folder inside main TeknoParrot folder
everything except opengl32.dll (INCLUDING SDL2.dll) to game folder, then setup via FFBPluginGUI.exe
