### ISSUE TITLE
BUG BUSTERS

### ISSUE THREAD

**Issue by unionjac13** [Boomslangnz/FFBArcadePlugin#66]
Bug Busters runs on intel graphics card will not run on  nvidia 3080ti just black screen no load please help

Thank You
unionjac1313

**Comment by Boomslangnz** [comment]
lol wtf is bug busters?

**Comment by unionjac13** [comment]
Sorry boom went to wrong place on git hub but could you fix the ffb on
crusin blast just does not work and I know ur the ffb genius please help if
you have time  thx much

**Comment by Boomslangnz** [comment]
What’s wrong with it? I’m no longer involved with TeknoParrot but they could get hold of me if they needed my help quite easily

**Comment by unionjac13** [comment]
I realize that but the motors down engage nothing happens. People are
switching DLLs and other things but supposedly big Mike is working on
something. Maybe you could lend them a hand as a favor anyway I hope
everything is good with you. You did a lot of work for us and we appreciate
it.

**Comment by Boomslangnz** [comment]
I don’t know who big Mike is or anything about it, I haven’t ever played the game even

**Comment by unionjac13** [comment]
Great game prolly nintendos biggest arcade game ever check it out on you
tube see what you think!!! Just wanted ffb support cherry to the pie….
