### ISSUE TITLE
knocking on moza R9

### ISSUE THREAD

**Issue by ToodlePeep** [Boomslangnz/FFBArcadePlugin#70]
FFB works and feels good, with the exception of a small clunking that happens what feels like every 2.5 seconds on the dot. Happens in all of the teknoparrot games I've tested so far, Wangan midnight 6, outrun, and daytona championship edition.

**Comment by ToodlePeep** [comment]
to clarify the knocking is a very brief shake of the wheel, like probably happening on a single frame, short to the point that I can't identify the direction it occurs in, but I can sure feel it.

**Comment by ToodlePeep** [comment]
FFB log is full of this

DLLMAIN ENTERED
process name:
C:\retro\teknoparrot\TeknoParrot\BudgieLoader.exe
default centering & friction values:
0
0
dll thread attach
DLLMAIN ENTERED
process name:
C:\retro\teknoparrot\TeknoParrot\BudgieLoader.exe
default centering & friction values:
0
0
dll thread attach
DLLMAIN ENTERED
process name:
C:\retro\teknoparrot\TeknoParrot\BudgieLoader.exe
default centering & friction values:
0
0
dll thread attach
DLLMAIN ENTERED
process name:
C:\retro\teknoparrot\TeknoParrot\BudgieLoader.exe
default centering & friction values:
0
0
dll thread attach
DLLMAIN ENTERED
process name:
C:\retro\teknoparrot\TeknoParrot\BudgieLoader.exe
default centering & friction values:
0

**Comment by ToodlePeep** [comment]
Randomly, even though it's a different error, I tried renaming opengl32.dll to winmm.dll for the /teknoparrot/teknoparrot directory  (based on this)and it appears to have fixed outrun only.

**Comment by ToodlePeep** [comment]
disregard everything I've written, it's turning off rumble/triggers that fixed it.

**Comment by jaoxford** [comment]
If it's fixed, can you close your issue?
