### ISSUE TITLE
Initial D 4, 5 crash when end of race.

### ISSUE THREAD

**Issue by Taekk2** [Boomslangnz/FFBArcadePlugin#72]
after 2.0.0.20 Initial D 4, 5 crash when end of race.
2.0.0.19 works well but crash reproduced after 2.0.0.20 to 2.0.0.37.

[log.zip](https://github.com/user-attachments/files/16122434/log.zip)

**Comment by Taekk2** [comment]
when issue reproduced, TriggerSineEffect function called with UINT16 period as 0.
I don't know why period as 0 even if not zero checked in InitialD4::FFBLoop ffb[1] > 0x00.

anyway i modified like below and issue cleared.
void TriggerSineEffect(UINT16 period, UINT16 fadePeriod, double strength)
{
	std::chrono::milliseconds now = duration_cast<milliseconds>(system_clock::now().time_since_epoch());
	long long elapsedTime = (std::chrono::duration_cast<std::chrono::milliseconds>(now - timeOfLastSineEffect)).count();

	int direction = 1;

	if (period < 1) {
		hlp.log("period < 1 reutrn");
		return;
	}


Log 
Doing sine...
8
Doing sine...
7
Doing sine...
6
Doing sine...
5
Doing sine...
4
Doing sine...
3
Doing sine...
2
Doing sine...
1
period < 1 reutrn

**Comment by Boomslangnz** [comment]
ok thanks, ill add that
