### ISSUE TITLE
Logitech g29 issue on outrun and crusin blast

### ISSUE THREAD

**Issue by Spazmoid1981** [Boomslangnz/FFBArcadePlugin#85]
Hi @Boomslangnz, thank you for an awesome ffb plugin - getting hours of joy out of these golden era of driving games with the plugin - I do have an issue with some games utilising force feedback on teknoparrot using Logitech g29 running on a win11 laptop pc (i9 and GeForce 4080) - the force feedback gui detects the wheel and works fine in setup within each executable folder but once I load outrun or crusin blast it doesn't create ffb in either of those games - others are fine such sr3 and Daytona swdc etc etc and I've tried everything I can think off to solve for these two games but I'm getting nowhere fast - I have ghub instaled and ffb works in mame using the plugin, and also in supermodel and model2 using their native ffb options - I've also tried reinstalling the files from the latest release and tecknopartot is on the latest version etc  - any ideas?

**Comment by Spazmoid1981** [comment]
@Boomslangnz @mightymikem so I solved the outrun issue by replacing the sdl2.dll file in teknoparrot folder with the one from ffb plugin...result but still no joy with crusin blast

**Comment by mightymikem** [comment]
Hey @Spazmoid1981 for cruisn you need to put the dlls in the elfldr2 folder did you try that

**Comment by Spazmoid1981** [comment]
@mightymikem thank you - ffb working now on crisis blast - guys you are legends - closing issue
