### ISSUE TITLE
FFB stopped working for Teknoparrot Outrun 2 SP SDX

### ISSUE THREAD

**Issue by Lazzarus666** [Boomslangnz/FFBArcadePlugin#89]
Outrun 2 SP SDX was working. I think it stopped working after an Teknoparrot update.   Update FFB to 2.0.0.53. No change still not working. Other Teknoparrot games are working fine with FFB on my setup. Seems to just be this one that's stopped

**Comment by Lazzarus666** [comment]
[FFBlog.txt](https://github.com/user-attachments/files/17528176/FFBlog.txt)

**Comment by Lazzarus666** [comment]
Found the logging in the ini. Attached log

**Comment by jaoxford** [comment]
Still not working?

**Comment by Lazzarus666** [comment]
Hi jaoxford. Unfortunately no. Just tested with the latest TeknoParrot.  FYI force feedback is working from the FFBPluginGUI test menu, just not in game

**Comment by Lazzarus666** [comment]
[FFBlog.txt](https://github.com/user-attachments/files/17952350/FFBlog.txt)

**Comment by jaoxford** [comment]
I also experienced this issue a few days ago.
It's not a problem with the FFB plugin. You need to rename some files and move one to a different directory.

https://www.reddit.com/r/teknoparrot/comments/1am8mtr/outrun2_sp_sdx_wont_run_with_ffb_plugin/

**Comment by Lazzarus666** [comment]
Success. Thanks for your help @jaoxford . 

For anyone else looking at this thread this is what i did:- 

1. Download [FFB Arcade Plugin Version 2.0.0.33]
2. Go to the Outrun 2 Special Tours Deluxe Real folder
3. Copy opengl32.dll into same folder. You should end up with a file called opengl32 - Copy.dll
4. Rename opengl32 - Copy.dll to winmm.dll
5. Copy winmm.dll, opengl32.dll and SDL2.dll to in to the teknoparrot folder inside your tknoparrot installed directory. Most likely  **teknoparrot/teknoparrot**
6. Copy everything in your 'Outrun 2 Special Tours Deluxe Real'  to your **Jennifer** folder in your Outrun game/rom folder
7. Run FFBPluginGUI and setup with your wheel
